ARG VARIANT="14"
FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:0-${VARIANT}

RUN cd / \
    && git clone --branch master https://github.com/audstanley/covid-app \
    && cd covid-app \
    && npm i \
    && cd .. \
    && mv covid-app code \
    && cd code \
    && chmod +x entrypoint.sh;

EXPOSE 3000